apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world-pod # Edit the main application container
          volumeMounts:
            - mountPath: /shared/java-agent # Mount the directory where the Java agent will be available
              name: java-agent
          env:
            - name: JAVA_OPTIONS # Instruct the JVM to load the Java agent
              value: -javaagent:/shared/java-agent/rook.jar
            - name: ROOKOUT_TOKEN # Make the token available as an environment variable
              valueFrom:
                secretKeyRef:
                  name: rookout
                  key: token
      initContainers: # Add an init container that will drop the Java agent to the shared volume
        - name: init-agent
          image: rookout/add-java-agent:latest
          volumeMounts:
            - mountPath: /shared/java-agent
              name: java-agent
      volumes: # Create the shared volume
        - name: java-agent
          emptyDir: {}
