apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
secretGenerator:
- name: rookout
  literals:
  - token=<ROOKOUT_TOKEN>
patchesStrategicMerge:
- java-agent.yaml