#!/bin/bash

# save incoming YAML from Helm to file
cat <&0 > kustomize/deployment.yaml

# Copy our original Kustomize config
cp ../kustomize/kustomization.yaml kustomize/
cp ../kustomize/java-agent.yaml kustomize/

# modify the YAML with kustomize and print it to the standard output
kustomize build kustomize

rm kustomize/*.yaml
